[2023-06-08T12:31:42.146+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.create_table manual__2023-06-08T12:31:41.621202+00:00 [queued]>
[2023-06-08T12:31:42.151+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.create_table manual__2023-06-08T12:31:41.621202+00:00 [queued]>
[2023-06-08T12:31:42.152+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-08T12:31:42.152+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-06-08T12:31:42.153+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-08T12:31:42.160+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2023-06-08 12:31:41.621202+00:00
[2023-06-08T12:31:42.165+0000] {standard_task_runner.py:55} INFO - Started process 223 to run task
[2023-06-08T12:31:42.168+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_postgres', 'create_table', 'manual__2023-06-08T12:31:41.621202+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/postgress_db.py', '--cfg-path', '/tmp/tmpgcpnv0gd']
[2023-06-08T12:31:42.169+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask create_table
[2023-06-08T12:31:42.218+0000] {task_command.py:388} INFO - Running <TaskInstance: database_postgres.create_table manual__2023-06-08T12:31:41.621202+00:00 [running]> on host 41b36ed2ff52
[2023-06-08T12:31:42.263+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=database_postgres
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T12:31:41.621202+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-08T12:31:41.621202+00:00
[2023-06-08T12:31:42.264+0000] {sql.py:254} INFO - Executing: drop table if exists users;
            CREATE TABLE IF NOT EXISTS USERS (
                id INT not null unique,
                name VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL,
                phone VARCHAR(255) NOT NULL,
                address VARCHAR(255) NOT NULL,
                organization VARCHAR(255) NOT NULL
            );
[2023-06-08T12:31:42.272+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-08T12:31:42.369+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-08T12:31:42.370+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

[2023-06-08T12:31:42.378+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=database_postgres, task_id=create_table, execution_date=20230608T123141, start_date=20230608T123142, end_date=20230608T123142
[2023-06-08T12:31:42.384+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task create_table (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
; 223)
[2023-06-08T12:31:42.424+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-08T12:31:42.441+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
