[2023-06-14T15:14:59.721+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.insert_into_table manual__2023-06-14T15:14:57.649319+00:00 [queued]>
[2023-06-14T15:14:59.730+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.insert_into_table manual__2023-06-14T15:14:57.649319+00:00 [queued]>
[2023-06-14T15:14:59.730+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T15:14:59.731+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-06-14T15:14:59.731+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T15:14:59.743+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2023-06-14 15:14:57.649319+00:00
[2023-06-14T15:14:59.748+0000] {standard_task_runner.py:55} INFO - Started process 334 to run task
[2023-06-14T15:14:59.765+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_postgres', 'insert_into_table', 'manual__2023-06-14T15:14:57.649319+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/postgress_db.py', '--cfg-path', '/tmp/tmpffg0iqdm']
[2023-06-14T15:14:59.774+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask insert_into_table
[2023-06-14T15:14:59.833+0000] {task_command.py:388} INFO - Running <TaskInstance: database_postgres.insert_into_table manual__2023-06-14T15:14:57.649319+00:00 [running]> on host 240567dc9ead
[2023-06-14T15:14:59.894+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=database_postgres
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-14T15:14:57.649319+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-14T15:14:57.649319+00:00
[2023-06-14T15:14:59.896+0000] {sql.py:254} INFO - Executing: INSERT INTO my_table (id,execution_time) VALUES (1,CURRENT_TIMESTAMP);
[2023-06-14T15:14:59.907+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-14T15:15:00.026+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-14T15:15:00.033+0000] {sql.py:375} INFO - Running statement: INSERT INTO my_table (id,execution_time) VALUES (1,CURRENT_TIMESTAMP);, parameters: None
[2023-06-14T15:15:00.035+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "execution_time" of relation "my_table" does not exist
LINE 1: INSERT INTO my_table (id,execution_time) VALUES (1,CURRENT_T...
                                 ^

[2023-06-14T15:15:00.047+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=database_postgres, task_id=insert_into_table, execution_date=20230614T151457, start_date=20230614T151459, end_date=20230614T151500
[2023-06-14T15:15:00.060+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 50 for task insert_into_table (column "execution_time" of relation "my_table" does not exist
LINE 1: INSERT INTO my_table (id,execution_time) VALUES (1,CURRENT_T...
                                 ^
; 334)
[2023-06-14T15:15:00.084+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-14T15:15:00.103+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
