[2023-06-14T13:39:49.924+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.get_all_timeofexecution manual__2023-06-14T13:39:45.989112+00:00 [queued]>
[2023-06-14T13:39:49.929+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_postgres.get_all_timeofexecution manual__2023-06-14T13:39:45.989112+00:00 [queued]>
[2023-06-14T13:39:49.930+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T13:39:49.930+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-06-14T13:39:49.931+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T13:39:49.938+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): get_all_timeofexecution> on 2023-06-14 13:39:45.989112+00:00
[2023-06-14T13:39:49.942+0000] {standard_task_runner.py:55} INFO - Started process 1042 to run task
[2023-06-14T13:39:49.945+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_postgres', 'get_all_timeofexecution', 'manual__2023-06-14T13:39:45.989112+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/postgress_db.py', '--cfg-path', '/tmp/tmpmqwpq40z']
[2023-06-14T13:39:49.946+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask get_all_timeofexecution
[2023-06-14T13:39:49.997+0000] {task_command.py:388} INFO - Running <TaskInstance: database_postgres.get_all_timeofexecution manual__2023-06-14T13:39:45.989112+00:00 [running]> on host 649eec7cdf92
[2023-06-14T13:39:50.066+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=database_postgres
AIRFLOW_CTX_TASK_ID=get_all_timeofexecution
AIRFLOW_CTX_EXECUTION_DATE=2023-06-14T13:39:45.989112+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-14T13:39:45.989112+00:00
[2023-06-14T13:39:50.068+0000] {sql.py:254} INFO - Executing: select * from my_table;
[2023-06-14T13:39:50.081+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-14T13:39:50.212+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-06-14T13:39:50.218+0000] {sql.py:375} INFO - Running statement: select * from my_table;, parameters: None
[2023-06-14T13:39:50.220+0000] {sql.py:384} INFO - Rows affected: 1
[2023-06-14T13:39:50.228+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 153, in default
    CLASSNAME: o.__module__ + "." + o.__class__.__qualname__,
AttributeError: 'datetime.datetime' object has no attribute '__module__'
[2023-06-14T13:39:50.237+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=database_postgres, task_id=get_all_timeofexecution, execution_date=20230614T133945, start_date=20230614T133949, end_date=20230614T133950
[2023-06-14T13:39:50.247+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task get_all_timeofexecution ('datetime.datetime' object has no attribute '__module__'; 1042)
[2023-06-14T13:39:50.279+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-06-14T13:39:50.296+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
